//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZMafia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int GameId { get; set; }
        public bool Alive { get; set; }
        public bool Mafia { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
